### ISSUE TITLE
Code highlight not working.

### ISSUE THREAD

**Issue by LuisDiazUgena** [kraih/atom-mojo#1]
Hi!

I'm working with your plugin and everything works fine until yesterday. Suddenly, code highlighting for mojolicious templates is not working.

I'm under atom 1.28.0 x64 on windows and using version 1.0.0 of the plugin.

I've uninstalled everything (atom, and deleted all related folders) and installed it again. No changes at all.

![image](https://user-images.githubusercontent.com/6543254/41774777-6dab1366-7621-11e8-8a58-5cb3815bb54e.png)

Thanks!

**Comment by kraih** [comment]
Afraid i no longer use Atom. So this plugin is unmaintained now.

**Comment by LuisDiazUgena** [comment]
Ok, no problem. Anyway, I found the issue!

If you place the env path for perl at the top of the file: ie:

`#!/usr/bin/perl`

It won't detect the highlighting. As soon as you remove it, it's ok.
